.TH "include/libft_additions.h" 3 "Fri Feb 9 2024" "Version 2024-02-09" "Push Swap" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/libft_additions.h
.SH SYNOPSIS
.br
.PP
\fC#include 'libft\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "long \fBft_abs\fP (int value)"
.br
.RI "\fBft_abs\fP -- Returns absolute value of int as long\&. "
.ti -1c
.RI "void * \fBft_dlclst_peek_offset\fP (t_dlclst *head, int offset)"
.br
.RI "\fBft_dlclst_peek_offset\fP -- Returns content of list element by offset from head\&. "
.ti -1c
.RI "void * \fBft_dlclst_peek_pos\fP (t_dlclst *lst, unsigned int pos)"
.br
.RI "\fBft_dlclst_peek_pos\fP -- Returns content of list element in position\&. "
.in -1c
.SH "Detailed Description"
.PP 
Set of additional generic functions needed for this project to be added in the future to libft\&. 
.SH "Function Documentation"
.PP 
.SS "long ft_abs (int value)"

.PP
\fBft_abs\fP -- Returns absolute value of int as long\&. 
.PP
\fBParameters\fP
.RS 4
\fIvalue\fP - Positive or negative integer\&.
.RE
.PP
\fBReturns\fP
.RS 4
A long positive value that is the absolute value of passed integer\&.
.RE
.PP
\fBWarning\fP
.RS 4
ft_abs(INT_MIN) returns a positive value greater than INT_MAX\&. 
.RE
.PP

.SS "void * ft_dlclst_peek_offset (t_dlclst * head, int offset)"

.PP
\fBft_dlclst_peek_offset\fP -- Returns content of list element by offset from head\&. Offset is signed and is interpreted as steps from head in the direction consistent with its sign (positive for next)\&.
.PP
\fBParameters\fP
.RS 4
\fIhead\fP - The head (first element) of the list\&.
.br
\fIoffset\fP - Positions from head in the next (positive offset) or the prev (negative offset) direction\&.
.RE
.PP
\fBReturns\fP
.RS 4
A void pointer to the content of the referenced element\&. 
.br
 NULL pointer is returned if head is NULL or the offset is invalid\&.
.RE
.PP
\fBWarning\fP
.RS 4
Offset absolute values greater than size are considered invalid and NULL is returned\&. 
.RE
.PP

.SS "void * ft_dlclst_peek_pos (t_dlclst * lst, unsigned int pos)"

.PP
\fBft_dlclst_peek_pos\fP -- Returns content of list element in position\&. Returns the content of the list element in position\&. TODO coletilla sobre la interpretacion circular de pos\&.
.PP
\fBParameters\fP
.RS 4
\fIlst\fP - The pointer to the first element of the list\&.
.br
\fIpos\fP - Position in the next direction from the head of the list\&.
.RE
.PP
\fBReturns\fP
.RS 4
A void pointer to the content of the referenced element\&. 
.br
 NULL pointer is returned if head is NULL or the offset is invalid\&.
.RE
.PP
\fBWarning\fP
.RS 4
Offset absolute values greater than size are considered invalid and NULL is returned\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Push Swap from the source code\&.
