.TH "include/ps_lang.h" 3 "Fri Feb 9 2024" "Version 2024-02-09" "Push Swap" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/ps_lang.h
.SH SYNOPSIS
.br
.PP
\fC#include 'ps_lang_types\&.h'\fP
.br
\fC#include 'ps_lang_init\&.h'\fP
.br
\fC#include 'ps_lang_peek\&.h'\fP
.br
\fC#include 'ps_lang_print\&.h'\fP
.br
\fC#include 'ps_lang_instructions\&.h'\fP
.br
\fC#include 'ps_lang_interpreter\&.h'\fP
.br

.SH "Detailed Description"
.PP 
Main (public) header file for the 'push swap language' and optional functions to implement the highest level of abstraction (based on an lower level doubly linked circular list implementation)\&. 
.br
 Each header file included here add features like: Supporting data structures and enums definitions\&. Other related fuctions collections for peeking values, memory allocation and freeing, initialization, printing, and others\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Push Swap from the source code\&.
