.TH "include/ps_lang_print.h" 3 "Fri Feb 9 2024" "Version 2024-02-09" "Push Swap" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/ps_lang_print.h
.SH SYNOPSIS
.br
.PP
\fC#include 'ps_lang_types\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBprint_stacks\fP (\fBt_ps_stacks\fP *ps)"
.br
.RI "\fBprint_stacks\fP -- Prints both stacks next to each other\&. "
.in -1c
.SH "Detailed Description"
.PP 
TODO Instructions for the 'push swap language' and optional functions to implement the highest level of abstraction (based on an lower level doubly linked circular list implementation)\&. 
.br
 Supporting data structures and fuctions for peeking values, memory allocation, initialization, printing, and others\&. 
.SH "Function Documentation"
.PP 
.SS "void print_stacks (\fBt_ps_stacks\fP * ps)"

.PP
\fBprint_stacks\fP -- Prints both stacks next to each other\&. Prints the content of both stack a and b\&. The uppermost element is the top of the stack\&.
.PP
\fBParameters\fP
.RS 4
\fIps\fP - The address of the pointer to the push swap stacks struct\&. 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Push Swap from the source code\&.
