.TH "s_ps_stacks" 3 "Fri Feb 9 2024" "Version 2024-02-09" "Push Swap" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s_ps_stacks \- Base for typedef \fBt_ps_stacks\fP for the main data structure for push_swap project\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ps_lang_types\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "t_dlclst * \fBa\fP"
.br
.ti -1c
.RI "t_dlclst * \fBb\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Base for typedef \fBt_ps_stacks\fP for the main data structure for push_swap project\&. 

This type is used as the main data structure for push_swap project\&. It contains both stack a and b implemented with doubly linked circular list implementation from libft\&. 
.SH "Field Documentation"
.PP 
.SS "s_ps_stacks::a"
Stack a to be initialized and sorted\&. 
.SS "s_ps_stacks::b"
Stack b to be used while sorting stack a elements\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Push Swap from the source code\&.
